A notebook for general purpose tests of library functionalities during development.

In [10]:
# concatenating numpy arrays
import numpy as np
xmin, xmax = 1.0, 10.0
nx = 11
xgrid = np.linspace(xmin, xmax, nx)
np.concatenate([[0.0], xgrid, [10.1]])

array([ 0. ,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. , 10.1])

In [17]:
# find indices
import numpy as np
np.random.seed(10)
nx = 10
test = np.random.randn(nx)
print(np.where(test < 0)[0])
print(np.where(test >= 0)[0])

[2 3 5 9]
[0 1 4 6 7 8]


In [21]:
# elementwise minimum / maximum
np.minimum(np.random.randn(5), np.random.randn(5))

array([-0.40013835, -1.90745689, -0.92290926,  0.46975143, -0.78726893])

In [ ]:
|